# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api_exception_subscriber:
        class: AppBundle\Controller\Api\ApiExceptionSubscriber
        arguments: ['%kernel.debug%']
        tags:
            - { name: kernel.event_subscriber }

    pagination_factory:
        class: AppBundle\Pagination\PaginationFactory
        arguments: ["@router"]

    event_factory:
        class: AppBundle\Service\EventFactory
        arguments: ["@doctrine.orm.entity_manager"]

    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        # autowire: true
        arguments: ['@lexik_jwt_authentication.encoder', '@doctrine.orm.entity_manager']